spring.security.user.name=oliver
spring.security.user.password=123

spring.datasource.url=jdbc:postgresql://localhost:5432/ChatApp
spring.datasource.username=postgres
spring.datasource.password=SzagosVagy645